name: dockerploy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
isar_version: 3.1.0

environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_modular: any
  google_fonts: any
  http: any
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  json_annotation: any
  objectbox_flutter_libs: any
  path_provider: any
  process_run: any
  reactive_dropdown_search: any
  reactive_forms: any
  reflectable: any
  shared_preferences: any
  simple_icons: any
  styled_widget: any
  flutter: 
    sdk: flutter
  window_size: 
    git: 
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies: 
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  isar_generator: 3.1.0
  json_serializable: any
  pubspec_dependency_sorter: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
